### ISSUE TITLE
deleteFlash is not working

### ISSUE THREAD

**Issue by atingupta2005** [anish6777/react-universal-flash#6]
Hi

I am using latest version of react but deleteFlash feature not working for me.
Please help

**Comment by anish6777** [comment]
Can you please provide the message component which you are using, deleteFlash is working as expected in the latest version. Please check the codesandbox below.  Maybe I will be able to help you out if you provide one minimal, reproducible example.

[Sample codesandbox with latest version and deleteFlash](https://codesandbox.io/s/react-universal-flash-material-ui-565761)
